name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: beyzasuna19
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push changes
        run: |
          git config --global user.name "beyzasuna19"
          git config --global user.email "beyzakambur2014@gmail.com"
          git add .
          git commit -m "Update snake animation"
          git push
